defaults:
  - base/base
  - _self_

base:
  dataset:
    batch_size: 1
    num_workers: 0
    transforms: ddd

model:
  _target_: src.models.detr.DETR
  name: DETR
  backbone: ResNet
  encoder: TransformerEncoder
  decoder: TransformerDecoder


optim:
  optimizer:
  learning_rate:
  scheduler:

runtime:
  epoch: 10
  