defaults:
  - base/base
  - _self_

base:
  dataset:
    batch_size: 1
    num_workers: 0
    transforms: ddd
    num_classes: 80

model:
  name: DETR
  backbone_name: 18
  num_heads: 8
  num_enc_layers: 6
  num_dec_layers: 6
  dim_ffn: 2048
  embed_dims: 256
  drop_rate: 0.5


criterion:
  name: DETRCriterion
  cls_weight: 0.1
  box_weight: 0.1
  iou_weight: 0.1

optim:
  optimizer:
  learning_rate:
  scheduler:

runtime:
  epoch: 10
  